import Head from 'next/head'
import { Container } from '../styles/pages/Home'

import Logo from '../assets/Machovka_case.svg'

const Home: React.FC = () => {
  return (
    <Container>
      <Head>
        <title>ReactJS | Next.js structure</title>
        <meta name="description" content="Generated by Erismar Oliveira" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Logo width="150" height="150" />
      <h1>ReactJS Structure</h1>
      <p>A ReactJS + Next.js structure.</p>
    </Container>
  )
}

export default Home
